---
- name: Create RHEL In Place Upgrade Inhibitors
  hosts: all
  become: yes
  tasks:
    - name: Enable SSH root login with password
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin yes'
      notify: Restart SSH
      when: ansible_distribution_major_version | int in [7, 8]

    - name: Enable SSH password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      notify: Restart SSH
      when: ansible_distribution_major_version | int in [7, 8]

    - name: Disable SSL for repos
      ansible.builtin.replace:
        path: "/etc/yum.repos.d/rhel{{ ansible_distribution_major_version | int + 1 }}-for-ripu.repo"
        regexp: '(?i)^\s*sslverify\s*=\s*1\s*$'
        replace: 'sslverify = 0'

    - name: Disable GPG for repos
      ansible.builtin.replace:
        path: "/etc/yum.repos.d/rhel{{ ansible_distribution_major_version | int + 1 }}-for-ripu.repo"
        regexp: '(?i)^\s*gpgcheck\s*=\s*1\s*$'
        replace: 'gpgcheck = 0'

    - name: Install interesting packages
      ansible.builtin.package:
        name: glibc-langpack-en
        state: present
      ignore_errors: yes
      when: ansible_distribution_major_version | int in [8, 9]

    - name: Add a remote root login with password that will cause a RHEL 8 inhibitor
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regex: "^(#)?{{ item.key }}"
        line: "{{ item.key }} {{ item.value }}"
        state: present
      loop:
        - {key: "PermitRootLogin", value: "yes"}
        - {key: "PasswordAuthentication", value: "yes"}
      notify:
        - Restart sshd
      when: ansible_distribution_major_version | int == 8

    - block:
        - name: Install nfs-utils package
          ansible.builtin.package:
            name: nfs-utils
            state: present
        - name: Add dummy entry in fstab with NFS
          ansible.builtin.lineinfile:
            path: /etc/fstab
            line: "rhpds-lab:/nfs/storage /nfsmnt nfs nofail,nobootwait,_netdev 0 0"
        - name: missing_efibootmgr | Uninstall the package
          ansible.builtin.package:
            name: efibootmgr
            state: absent
        - name: corrupted_grubenv_file | Copy corrupted grub file
          ansible.builtin.copy:
            dest: "/boot/grub.conf"
            content: "All your base are belong to us"
        - name: cifs_detected | Install cifs-utils package
          ansible.builtin.package:
            name: cifs-utils
            state: present
        - name: cifs_detected | Add dummy entry in fstab with CIFS
          ansible.builtin.lineinfile:
            path: /etc/fstab
            line: "//bontregerdev/storage /mnt cifs nofail,nobootwait,credentials=/root/smb.cred,_netdev 0 0"
        - name: Remove PermitRootLogin line
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^PermitRootLogin'
            state: absent
      when: ansible_distribution_major_version | int == 7
        

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted